### ISSUE TITLE
test các chức năng bằng postman

### ISSUE THREAD

**Issue by LienNTB** [datdnthcmute/VideoServer_Group20#49]
test các chức năng: được chia thành 7 task như sau
# _**task1:**_

## 1. List all projects
- [x] List all projects

## 2. Create project

- [x] Create a project SUCCESS
- [x] Create a project ERROR

## 3. Retrieve project details

- [x] Retrieve project details FOUND
- [x] Retrieve project details NOT FOUND

# _**task2:**_

## 4. Delete a project

- [x] Delete a project SUCCESS
- [x] Delete a project FAIL

## 5. Duplicate a project

- [x] Duplicate a project SUCCESS
- [x] Duplicate a project FAIL

# **_task3:_**

### Trim

- [x] Trim Video BAD REQUEST
- [x] Trim Video SUCCESS
- [x] Trim Video NOT FOUND
- [x] Trim Video CONFLICT

### Rotate

- [x] Rotate Video BAD REQUEST
- [x] Rotate Video SUCCESS
- [x] Rotate Video SUCCESS
- [x] Rotate Video CONFLICT

# _**task4:**_

### Scale

- [x] Scale Video BAD REQUEST
- [x] Scale Video SUCCESS
- [x] Scale Video NOT FOUND
- [x] Scale Video CONFLICT

### Crop

- [x] Crop Video BAD REQUEST
- [x] Crop Video SUCCESS
- [x] Crop Video NOT FOUND
- [x] Crop Video CONFLICT

# _**task5:**_

## 7. Capture a thumbnail for a preview at a certain position

- [x] Capture a thumbnail for a preview at a certain position BAD REQUEST
- [x] Capture a thumbnail for a preview at a certain position SUCCESS
- [x] Capture a thumbnail for a preview at a certain position CONFLICT
- [x] Capture a thumbnail for a preview at a certain position NOT FOUND
- [x] Capture a thumbnail for a preview at a certain position with **edit position**(crop, rotate) SUCCESS

# _**task6:**_

## 8. Capture timeline thumbnails 

- [x] Capture timeline thumbnails BAD REQUEST
- [x] Capture timeline thumbnails SUCCESS
- [x] Capture timeline thumbnails NOT FOUND

## 9. Upload a custom image file for a preview thumbnail

- [x] Upload a custom image file for a preview thumbnail

# _**task7:**_

## 10. Get preview thumbnail file

- [x] Get preview thumbnail file

## 11. Get timeline thumbnail file

- [x] Get timeline thumbnail file

## 12. Get video stream

- [x] Get video stream

**Comment by datdnthcmute** [comment]
Vui lòng tải về và xem report testing trong link sau:
`https://drive.google.com/drive/folders/12Xu3KOX_nZSPV8-s8akW382TRfNlWklN?usp=sharing`
