### ISSUE TITLE
Tìm hiểu về AWS (Amazon Web Services)

### ISSUE THREAD

**Issue by datdnthcmute** [datdnthcmute/VideoServer_Group20#53]
- [x] Day 19/4/2023: Tìm hiểu AWS và các dịch vụ có thể deploy
- [x] Day 20/4/2023: Tạo tài khoản AWS và cấu hình đăng nhập đúng cách
- [x] Day 21/4/2023: Tạo và quản lý các EC2 instances (các máy chủ ảo)

**Comment by LienNTB** [comment]
task 19/4: tìm hiểu về aws qua tài liệu chính thức của amazon https://docs.aws.amazon.com/ 
Amazon Web Services (AWS) là một nền tảng đám mây (cloud computing platform) được cung cấp bởi Amazon. Nó cung cấp một loạt các dịch vụ đám mây, bao gồm máy chủ ảo, lưu trữ đám mây, cơ sở dữ liệu đám mây, các dịch vụ tính toán và các công cụ phát triển ứng dụng. AWS cho phép các tổ chức, doanh nghiệp và nhà phát triển tạo ra và triển khai các ứng dụng và dịch vụ trên nền tảng đám mây một cách nhanh chóng và linh hoạt hơn bằng cách tránh các vấn đề về cơ sở hạ tầng, bảo mật và quản lý dữ liệu. AWS được xem là một trong những nhà cung cấp đám mây lớn nhất và phổ biến nhất trên thế giới.

- Các dịch vụ của aws có thể deploy docker được là
AWS cung cấp nhiều dịch vụ hỗ trợ việc triển khai Docker, bao gồm:

Amazon Elastic Container Service (Amazon ECS): Dịch vụ quản lý container của AWS, cho phép bạn triển khai và quản lý các ứng dụng chạy trên container Docker trên AWS.

Amazon Elastic Kubernetes Service (Amazon EKS): Dịch vụ quản lý Kubernetes của AWS, cho phép bạn triển khai các ứng dụng chạy trên container Docker trên cụm Kubernetes được quản lý bởi AWS.

AWS Fargate: Dịch vụ quản lý container của AWS, cho phép bạn triển khai các ứng dụng chạy trên container Docker mà không cần quản lý cụm máy chủ.

AWS Elastic Beanstalk: Dịch vụ quản lý ứng dụng của AWS, cho phép bạn triển khai các ứng dụng chạy trên container Docker một cách dễ dàng bằng các mô-đun được cung cấp sẵn.

Ngoài ra, AWS còn cung cấp các dịch vụ khác như Amazon EC2 Container Registry (ECR) để lưu trữ và quản lý các hình ảnh Docker, và Amazon CodeDeploy để triển khai các ứng dụng trên nhiều môi trường khác nhau.

**Comment by LienNTB** [comment]
task 20/4: tạo tài khoản cá nhân thành công
![image](https://user-images.githubusercontent.com/94447923/234253339-38390994-f500-476f-a3fb-23b6e777ee69.png)

**Comment by LienNTB** [comment]
task 21/4: 
![image](https://user-images.githubusercontent.com/94447923/234253859-a353ca11-09ff-462d-b8fb-69d5bbd3cc9c.png)
