### ISSUE TITLE
Tìm hiểu về Docker File và cách deploy 

### ISSUE THREAD

**Issue by datdnthcmute** [datdnthcmute/VideoServer_Group20#54]
- [x] Day 22/4/2023: Tìm hiểu về Docker file
- [x] Day 23/4/2023: Tìm hiểu cách deploy docker file bằng AWS

**Comment by LienNTB** [comment]
task 22/4: 

- tìm hiểu về docker qua tài liệu https://docker-curriculum.com/ 
- bên cạnh đó tìm hiểu về docker file và phân biệt được khi nào thì sử dụng docker file khi nào sử dụng docker compose

**Comment by LienNTB** [comment]
task 23/4: 

- tìm hiểu thử deploy projcect docker
- build project docker và push images lên docker hub
![image](https://user-images.githubusercontent.com/94447923/234255372-0b4a93f6-6b3d-44c0-8ad4-c5463cf487f1.png)

- sử dụng dịch vụ aws Elastic Beanstalk để deploy -> tạo các application và environment 
![image](https://user-images.githubusercontent.com/94447923/234255929-183353b2-8bb8-469f-953d-34d0d3f02cd3.png)

- Tạo file Dockerrun.aws.json để deploy
![image](https://user-images.githubusercontent.com/94447923/234256073-5ab40f8c-31f0-404b-ba93-143e672f7e06.png)

- deploy thành công với docker file (chỉ hỗ trợ 1 image, 1 container nên deploy project chưa hoàn tất còn thiếu db mongodb và  rabbitmq)
 ![image](https://user-images.githubusercontent.com/94447923/234256320-4f4f2969-ab13-4ee1-86e0-9eb63404c829.png)
