### ISSUE TITLE
Mô tả chung về đề tài

### ISSUE THREAD

**Issue by LienNTB** [datdnthcmute/VideoServer_Group20#6]
phạm vị, các mục tiêu, quy trình

**Comment by LienNTB** [comment]
Task ngày 15/3
-	Các nội dung chính của đồ án
    o	Tìm hiểu service lưu trữ, edit video trước đó: https://github.com/superdesk/video-server
    o	Xác định được mục tiêu chính của project
    o	Tìm hiểu và xây dựng thêm frontend cho project 
    o	Xây dựng document + quản lý dự án
    o	Xây dựng kết hoạch test, test case
    o	Deployment
-	Giới thiệu
Videoserver là trình lưu trữ và chỉnh sửa video API Web HTTP cho phép người sử dụng tạo dự án video và edit dựa trên ngôn ngữ lập trình python. với các tác vụ phổ biến như cắt, ghép, chỉnh sửa khung hình cũng như thêm hình ảnh.
-	Mục tiêu
Xây dựng một website cung cấp dịch vụ lưu trữ và chỉnh sửa video. Giao diện hệ thống trực quan, chức năng phù hợp và thuận tiện đảm bảo được yêu cầu của đề tài.

**Comment by datdnthcmute** [comment]
Task ngày 15/3, 16/3, 18/3, 20/3: https://docs.google.com/document/d/1L5dLmfruEs58lzRTmhRHStZ7JbNZ0TbvUCFL8PWjtcU/edit?usp=sharing
