### ISSUE TITLE
Xác định môi trường, ngôn ngữ và framework của project

### ISSUE THREAD

**Issue by LienNTB** [datdnthcmute/VideoServer_Group20#9]

**Comment by datdnthcmute** [comment]
## **Ngôn ngữ sử dụng**
- Python

##**Môi trường**
_Cài đặt môi trường theo yêu cầu của các version sau_
- Python (>=3.6)
- FFmpeg
- MongoDB
- RabbitMQ

##**Cài đặt để phát triển**
####_LƯU Ý: Sử dụng virtualenv và pip để cài đặt các module python._
Tại thư mục ta setup code
**git clone https://github.com/superdesk/video-server.git**
Cài đặt máy chủ video để phát triển
LƯU Ý: virtualenv của bạn phải được kích hoạt
pip install -e video-server/[dev]
